[project]
name = "pypi-security-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.11.3",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.30",
    "requests>=2.32.5",
]
